import json
import sys
import os

VERIFIED_JSON = "verified_sources.json"
OUTPUT_FILE = "rocm-overlay.nix"

# --- 1. Semantic Mapping Layer ---
# Maps XML Repo Names -> Nixpkgs Attribute Names
NAME_MAPPING = {
    "ROCm-CompilerSupport": "rocm-comgr",
    "ROCm-Device-Libs": "rocm-device-libs",
    "ROCR-Runtime": "rocm-runtime",
    "clr": "clr",
    "HIP": "hip-common",
    "ROCm-OpenCL-Runtime": "rocm-opencl-runtime",
    "ROCT-Thunk-Interface": "roct-thunk-interface", # Critical Gap 1: Thunk
    "rocm-cmake": "rocm-cmake",                     # Critical Gap 2: Build Macros
    "MIOpen": "miopen",
    "rocBLAS": "rocblas",
    "rocminfo": "rocminfo",
    "llvm-project": "llvm-project"                  # Special handling below
}

# --- 2. Intervention Layer ---
# Components that MUST have old patches/hooks stripped
STRIP_PATCHES = {
    "rocm-runtime", "clr", "rocm-comgr", 
    "rocm-device-libs", "hip-common", "llvm", "clang"
}

# --- 3. Custom Fix Injection Layer ---
CUSTOM_FIXES = {
    "roct-thunk-interface": '''
      # Fix Gap: Runtime expects libraries in /lib, not /lib64
      postInstall = "rm -rf $out/lib64 && ln -s lib $out/lib64 || true";
    ''',
    
    "rocm-cmake": '''
      # Fix Gap: Ensure macros are compatible with 7.2
    ''',

    "rocm-comgr": '''
      cmakeFlags = (old.cmakeFlags or []) ++ [
        "-DCMAKE_PREFIX_PATH=${finalScope.rocm-device-libs}"
      ];
    ''',

    "rocm-runtime": '''
      cmakeFlags = (old.cmakeFlags or []) ++ [
         "-DCMAKE_PREFIX_PATH=${finalScope.rocm-device-libs}"
         "-DIMAGE_SUPPORT=OFF"
      ];
    ''',

    "clr": '''
      nativeBuildInputs = (old.nativeBuildInputs or []) ++ [ final.git final.llvmPackages_17.clang ];
      postPatch = ''
        patchShebangs .
        # Fix clang path in hip_embed_pch.sh
        sed -i "s|\\$4/bin/clang|${final.llvmPackages_17.clang}/bin/clang|g" hipamd/src/hip_embed_pch.sh
      '';
      cmakeFlags = (old.cmakeFlags or []) ++ [
        "-DCMAKE_PREFIX_PATH=${finalScope.rocm-device-libs}"
        "-DAMDGPU_TARGETS=gfx1151;gfx1100" # Explicit Strix Halo Support
      ];
    '''
}

PHASE4_SHELLHOOK = '''
      shellHook = ''
        export LLAMA_HIP_UMA=ON
        export HSA_XNACK=1
        export HSA_OVERRIDE_GFX_VERSION=11.5.1
      '';
'''

def main():
    try:
        if os.path.exists(VERIFIED_JSON):
            with open(VERIFIED_JSON, "r") as f:
                sources = json.load(f)
        else:
             print(f"Warning: {VERIFIED_JSON} not found.")
             return
    except Exception as e:
        print(f"Error: {e}")
        return

    nix_code = []
    nix_code.append("# ROCm 7.2.0 Overlay - Generated by Intelligent Automation V2")
    nix_code.append("final: prev: {")
    nix_code.append("  rocmPackages = prev.rocmPackages.overrideScope (finalScope: prevScope: {")
    
    llvm_src = None

    # First Pass: Capture Sources
    source_map = {s["name"]: s for s in sources if s.get("status") == "OK"}

    # Handle LLVM Source Extraction
    if "llvm-project" in source_map:
        llvm_data = source_map["llvm-project"]
        llvm_rev = llvm_data["rev"]
        llvm_hash = llvm_data["sha256"]
        llvm_url = llvm_data.get("url", "https://github.com/ROCm/llvm-project")
        
        # --- FIX GAP 3: BOOTSTRAP TOOLCHAIN ---
        nix_code.append(f'''
    # Toolchain Bootstrap: Override LLVM & Clang with ROCm 7.2 Source
    llvm = prevScope.llvm.overrideAttrs (old: {{
      version = "7.2.0";
      src = final.fetchgit {{
        name = "llvm-src";
        url = "{llvm_url}";
        rev = "{llvm_rev}";
        sha256 = "{llvm_hash}";
        fetchSubmodules = true;
      }};
      # Ensure Strix Halo target is built
      cmakeFlags = (old.cmakeFlags or []) ++ [ "-DLLVM_TARGETS_TO_BUILD=AMDGPU;X86" ];
    }});

    clang = prevScope.clang.overrideAttrs (old: {{
      version = "7.2.0";
      src = final.fetchgit {{
        name = "clang-src";
        url = "{llvm_url}";
        rev = "{llvm_rev}";
        sha256 = "{llvm_hash}";
        fetchSubmodules = true;
      }};
    }});
        ''')

    # Standard Loop
    for repo_name, src in source_map.items():
        if repo_name == "llvm-project": continue # Handled above

        nix_attr = NAME_MAPPING.get(repo_name, repo_name)
        rev = src["rev"]
        sha256 = src["sha256"]
        url = src.get("url", f"https://github.com/ROCm/{repo_name}")

        nix_code.append(f"    {nix_attr} = prevScope.{nix_attr}.overrideAttrs (old: {{")
        nix_code.append(f'      version = "7.2.0";')
        nix_code.append(f'      src = final.fetchgit {{')
        nix_code.append(f'        name = "{nix_attr}-src";')
        nix_code.append(f'        url = "{url}";')
        nix_code.append(f'        rev = "{rev}";')
        nix_code.append(f'        sha256 = "{sha256}";')
        nix_code.append(f'        fetchSubmodules = true;')
        nix_code.append(f'      }};')

        if nix_attr in STRIP_PATCHES:
             nix_code.append('      patches = [];')
        
        if nix_attr in CUSTOM_FIXES:
            nix_code.append(CUSTOM_FIXES[nix_attr])

        nix_code.append("    });")

    # --- FIX GAP 3 (CONT): Override Stdenv ---
    nix_code.append('''
    # Force the environment to use the new 7.2.0 Clang
    rocmClangStdenv = prevScope.rocmClangStdenv.override {
      cc = finalScope.clang;
    };
    ''')

    nix_code.append("  });")
    
    # Expose key packages
    nix_code.append("  rocm-runtime = final.rocmPackages.rocm-runtime;")
    nix_code.append("  clr = final.rocmPackages.clr;")
    
    nix_code.append(f'  {PHASE4_SHELLHOOK.strip()}')
    nix_code.append("}")
    
    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(nix_code))
    
    print(f"✅ Generated {OUTPUT_FILE} with Toolchain Bootstrap & Semantic Fixes.")

if __name__ == "__main__":
    main()